spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/os26}
    username:  ${DB_USERNAME:postgres}
    password:  ${DB_PASSWORD:1234}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: true
    change-log: ${LIQUIBASE_CHANGE-LOG:classpath:db/postgres/changelogs.yaml}
    contexts: dev
  application:
    name: ${APPLICATION_NAME:orderService }
  main:
    allow-circular-references: true
server:
  port: ${SERVER_PORT:8484}
keycloak:
  auth-server-url: ${KEYCLOAK_URL:http://localhost:8080/auth}
  realm: ${KEYCLOAK_REALM:my_realm}
  resource: ${KEYCLOAK_RESOURCE:my_client}
  public-client: true