spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pr5
    username: postgres
    password: 1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/v1_1.yaml
    contexts: dev
  application:
    name: ${APPLICATION_NAME:myProject}
  main:
    allow-circular-references: true
server:
  port: ${SERVER_PORT:8484}
keycloak:
  auth-server-url: http://localhost:8080/auth
  realm: my_realm
  resource: my_client
  public-client:  true