spring:
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
  liquibase:
    enabled: true
    change-log: ${LIQUIBASE_CHANGE-LOG:classpath:h2/changelogs.yaml}
    contexts: dev
  application:
    name: ${APPLICATION_NAME:orderService}
  main:
    allow-circular-references: true
