spring:
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: sa
    password:
  liquibase:
    enabled: true
    change-log: ${LIQUIBASE_CHANGE-LOG:classpath:h2/changelog/changelogs.yaml}
    contexts: dev
    user: sa
    password:
  application:
    name: ${APPLICATION_NAME:orderService}
  main:
    allow-circular-references: true



